apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-blob-auth
  namespace: k4s-project
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-blob-scaledobject
  namespace: k4s-project
spec:
  minReplicaCount: 0
  maxReplicaCount: 100
  pollingInterval: 10 # Optional. Default: 30 seconds
  cooldownPeriod: 5 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: main-app
  triggers:
    - type: azure-blob
      metadata:
        accountName: sela90188
        blobContainerName: "keda" # Required: Name of Azure Blob Storage container
        blobCount: "2" # Optional. Amount of blobs to scale out on. Default: 5 blobs
        blobPrefix: "" # Optional. Prefix for the Blob. Use this to specifiy sub path for the blobs if required. Default : ""
      authenticationRef:
        name: azure-blob-auth